import AppKit

/// Élément de l'historique du presse-papiers.
struct ClipboardItem: Identifiable, Codable, Equatable, Sendable {
    enum Content: Codable, Equatable, Sendable {
        case text(String)
        /// Image PNG (limitée en taille, voir `ClipboardReader.maxImageBytes`).
        case image(Data)
        /// Fichiers copiés dans le Finder.
        case files([URL])
    }

    let id: UUID
    let content: Content
    let copiedAt: Date
    /// App d'où vient la copie (si connue).
    let sourceApp: String?
    var isPinned = false

    init(content: Content, copiedAt: Date = Date(), sourceApp: String? = nil) {
        id = UUID()
        self.content = content
        self.copiedAt = copiedAt
        self.sourceApp = sourceApp
    }

    /// Même contenu (pour éviter les doublons dans l'historique).
    func hasSameContent(as other: ClipboardItem) -> Bool {
        content == other.content
    }

    /// Texte court pour l'affichage.
    var preview: String {
        switch content {
        case let .text(text):
            return text.trimmingCharacters(in: .whitespacesAndNewlines)
                .replacingOccurrences(of: "\n", with: " ")
        case .image:
            return String(localized: "Image")
        case let .files(urls):
            return urls.count == 1 ? urls[0].lastPathComponent : String(localized: "\(urls.count) fichiers")
        }
    }
}

/// Lecture et écriture du presse-papiers, avec les règles de confidentialité.
enum ClipboardReader {
    /// Types posés par les gestionnaires de mots de passe et les apps pour signaler un contenu
    /// confidentiel, temporaire ou généré automatiquement : on ne le garde jamais.
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    static let maxTextLength = 20_000
    static let maxImageBytes = 4 * 1024 * 1024

    /// Faut-il ignorer ce contenu (confidentiel, temporaire) ?
    static func shouldIgnore(types: [String]) -> Bool {
        types.contains { ignoredTypes.contains($0) }
    }

    /// Contenu actuel du presse-papiers, ou `nil` s'il est vide, confidentiel ou non pris en charge.
    @MainActor
    static func read(_ pasteboard: NSPasteboard = .general) -> ClipboardItem.Content? {
        let types = pasteboard.types?.map(\.rawValue) ?? []
        guard !types.isEmpty, !shouldIgnore(types: types) else { return nil }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls)
        }
        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .text(String(text.prefix(maxTextLength)))
        }
        if let image = NSImage(pasteboard: pasteboard),
           let tiff = image.tiffRepresentation,
           let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]),
           png.count <= maxImageBytes {
            return .image(png)
        }
        return nil
    }

    /// Recopie un élément dans le presse-papiers.
    @MainActor
    static func write(_ content: ClipboardItem.Content, to pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        switch content {
        case let .text(text):
            pasteboard.setString(text, forType: .string)
        case let .image(data):
            if let image = NSImage(data: data) { pasteboard.writeObjects([image]) }
        case let .files(urls):
            pasteboard.writeObjects(urls as [NSURL])
        }
    }
}
